# Refs to https://github.com/hugo-fixit/docs/blob/main/config/_default/params.zh-cn.toml

# -------------------------------------------------------------------------------------
# Theme Core Configuration | ä¸»é¢˜æ ¸å¿ƒé…ç½®
# See: https://fixit.lruihao.cn/zh-cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

description = "å·¥ä½œè®°å½• - æŸäºº"

[gitInfo]
  dir = "content/zh-cn"

[author]
  name = "Somebody"
  email = ""
  link = ""
  avatar = "/images/avatar.png"

[home]
  [home.profile]
    subtitle = "å“ˆå–½ ğŸ‘‹, æ•´ç‚¹ç”œç”œåœˆåƒåƒå§"

[watermark]
  content = '<img class="fixit-icon" src="/images/hugo-somebody.webp" alt="FixIt logo" /> Someone work notes'
